In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from pandas.api.types import is_numeric_dtype

In [ ]:
df = pd.read_csv('insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()

# Manually Encoding -> Label Encoding

In [ ]:
df1.shape

(1338, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df1.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [16]:
for col in df1.columns:
    if is_numeric_dtype(df1[col]):
        continue
    else:
        uni = df1[col].unique()
        #print(uni)
        if len(uni) == 2:
            df1[col] = df1[col].replace(uni, [0,1])
        if len(uni) == 3:
            df1[col] = df1.col.replace(uni, [0,1,2])
        if len(uni) == 4:
            df1[col] == df1[col].replace(uni,[0,1,2,3])

C:\Users\Qbits\AppData\Local\Temp\ipykernel_13912\796895068.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1[col] = df1[col].replace(uni, [0,1])
C:\Users\Qbits\AppData\Local\Temp\ipykernel_13912\796895068.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1[col] == df1[col].replace(uni,[0,1,2,3])

In [17]:
df1

      age  sex     bmi  children  smoker     region      charges
0      19    0  27.900         0       0  southwest  16884.92400
1      18    1  33.770         1       1  southeast   1725.55230
2      28    1  33.000         3       1  southeast   4449.46200
3      33    1  22.705         0       1  northwest  21984.47061
4      32    1  28.880         0       1  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    1  30.970         3       1  northwest  10600.54830
1334   18    0  31.920         0       1  northeast   2205.98080
1335   18    0  36.850         0       1  southeast   1629.83350
1336   21    0  25.800         0       1  southwest   2007.94500
1337   61    0  29.070         0       0  northwest  29141.36030

[1338 rows x 7 columns]

# Label Encoding -> Using scikit learn library

In [18]:
df2.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [19]:
df2.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [20]:
le = LabelEncoder()
for col in df2.columns:
    if is_numeric_dtype(df2[col]):
        continue
    else:
        df2[col] = le.fit_transform(df2[col])

In [21]:
df2

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

#  OneHotEncoding -> Manually

In [34]:
df3

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [35]:
dummy = pd.get_dummies(df3['sex'], drop_first=True).astype(int)
dummy

      male
0        0
1        1
2        1
3        1
4        1
...    ...
1333     1
1334     0
1335     0
1336     0
1337     0

[1338 rows x 1 columns]

In [36]:
df3 = df3.drop('sex',axis = 1)

In [37]:
df3

      age     bmi  children smoker     region      charges
0      19  27.900         0    yes  southwest  16884.92400
1      18  33.770         1     no  southeast   1725.55230
2      28  33.000         3     no  southeast   4449.46200
3      33  22.705         0     no  northwest  21984.47061
4      32  28.880         0     no  northwest   3866.85520
...   ...     ...       ...    ...        ...          ...
1333   50  30.970         3     no  northwest  10600.54830
1334   18  31.920         0     no  northeast   2205.98080
1335   18  36.850         0     no  southeast   1629.83350
1336   21  25.800         0     no  southwest   2007.94500
1337   61  29.070         0    yes  northwest  29141.36030

[1338 rows x 6 columns]

In [38]:
df3 = pd.concat((df3, dummy), axis = 1)
df3

      age     bmi  children smoker     region      charges  male
0      19  27.900         0    yes  southwest  16884.92400     0
1      18  33.770         1     no  southeast   1725.55230     1
2      28  33.000         3     no  southeast   4449.46200     1
3      33  22.705         0     no  northwest  21984.47061     1
4      32  28.880         0     no  northwest   3866.85520     1
...   ...     ...       ...    ...        ...          ...   ...
1333   50  30.970         3     no  northwest  10600.54830     1
1334   18  31.920         0     no  northeast   2205.98080     0
1335   18  36.850         0     no  southeast   1629.83350     0
1336   21  25.800         0     no  southwest   2007.94500     0
1337   61  29.070         0    yes  northwest  29141.36030     0

[1338 rows x 7 columns]

In [41]:
# uSING LOOP
df4

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [43]:
for col in df4.columns:
    if is_numeric_dtype(df4[col]):
        continue
    else:
        dum = pd.get_dummies(df4[col], drop_first = True, prefix = col).astype(int)
        df4 = df4.drop(col, axis = 1)
        df4 = pd.concat((df4, dum), axis = 1)

In [44]:
df4

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,0,1,0,0,1
1,18,33.770,1,1725.55230,1,0,0,1,0
2,28,33.000,3,4449.46200,1,0,0,1,0
3,33,22.705,0,21984.47061,1,0,1,0,0
4,32,28.880,0,3866.85520,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,1,0,1,0,0
1334,18,31.920,0,2205.98080,0,0,0,0,0
1335,18,36.850,0,1629.83350,0,0,0,1,0
1336,21,25.800,0,2007.94500,0,0,0,0,1
1337,61,29.070,0,29141.36030,0,1,1,0,0

In [45]:
# Ordinal Encoding

In [47]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [49]:
df5

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [53]:
df5['sex'] = oe.fit_transform(df5[['sex']])
df5

      age  sex     bmi  children smoker     region      charges
0      19  0.0  27.900         0    yes  southwest  16884.92400
1      18  1.0  33.770         1     no  southeast   1725.55230
2      28  1.0  33.000         3     no  southeast   4449.46200
3      33  1.0  22.705         0     no  northwest  21984.47061
4      32  1.0  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50  1.0  30.970         3     no  northwest  10600.54830
1334   18  0.0  31.920         0     no  northeast   2205.98080
1335   18  0.0  36.850         0     no  southeast   1629.83350
1336   21  0.0  25.800         0     no  southwest   2007.94500
1337   61  0.0  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]